version: '3.5'
services:
  OnboardingService:
   image: ${DOCKER_REGISTRY-}onboardingmicroservice:v1
   build:
    context: ./Onboarding
    dockerfile: Dockerfile
   environment: 
    - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=192.168.1.6,1433;Initial Catalog=ProductServiceDB;User Id=sa;Password=database@1
   ports:
    - "4201:80"
  
  db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"